<?php
/*
 * @file trying to create a airpot field module
 * extensively using field api
 */

/*
 * implements hook_field_info()
 */

function airport_field_field_info()
{
    $field = array();
    $field['airport_field'] = array(
        'label' => t('Airports'),
        'description' => t('Provides list of airports with name codes'),
        'default_widget' => 'airport_code',
        'default_formatter' => 'airport_raw',
    );
    return $field;


}
/*
 * Implements hook_filed_widget_info();
 */
function airport_field_field_widget_info(){
    return array(
        'airport_code'=>array(
            'label' =>' Autocomplete Code widget',
            'field types' => array('airport_field'),
        ),
        'airport_name'=>array(
            'label' => 'Autocomplete Name Widget',
            'field types' => array('airport_field'),
        ),
        'airport_name_code' => array(
            'label' => 'Autocmplete both code and name Widget',
            'field types' => array('airport_field'),
        ),
    );

}
/*
 * implements hook_field_widget_form()
 */
function airport_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
    $element['code'] = array(
        '#type' => 'textfield',
        '#prefix' => 'Airport Code',
        '#attributes' => array('class'=>array('airport-codes')),
        '#size' => 4,
        '#default_value' => isset($items[$delta]['code']) ? $items[$delta]['code']: '',
    );
    return $element;
}

/*
 * Implements hook_field_formatter_info()
 */
function airport_field_field_formatter_info(){
    return array(
        'airport_raw'=>array(
        'label' => t('Autocomplete Airport'),
        'field types' => array('airport_field'),
        ),

    );
}







